name: GUI, API and Components Tests

on:
  push:
    branches:
      - main  

jobs:
  dependencies-install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
      

  gui-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install frontend
        run: npm run install:frontend

      - name: Install backend
        run: npm run install:backend

      - name: Run GUI tests
        run: npm run gui:run

  component-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install frontend
        run: npm run install:frontend

      - name: Install backend
        run: npm run install:backend

      - name: Run component tests
        run: npm run component:run

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install backend
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:backend
          runTests: false
      - name: Install frontend
        uses: cypress-io/github-action@v6
        with:
          install-command: npm run install:frontend
          runTests: false
      - name: Run API tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run start:frontend, npm run start:server
          command: npm run api:run