name: GUI, API and Components Tests

on:
  push:
    branches:
      - main  

jobs:
  dependencies-install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install frontend
        run: npm run install:frontend

      - name: Install backend
        run: npm run install:backend
      

  gui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run GUI tests
        run: npx cypress run --spec cypress/e2e/gui-tests/**.cy.js --record false

  component-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run component tests
        run: npx cypress run --component --record false

  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run API tests
        run: ./node_modules/cypress/bin/cypress install && npm run api:run
