name: ESLint

on:
  push:
    branches:
      - main


jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install globals
        run: npm i -D globals

      - name: Run ESLint
        run: npm run lint